### ISSUE TITLE
Incorrect visualized text span (Follow up of #1009)

### ISSUE THREAD

**Issue by TMWong** [nlplab/brat#1014]
This is a follow up problem of #1009.

Using the latest codes I can now at least get the visualization output. However, a strange error occurs that two different ranges starting with the same position:
![image](https://f.cloud.github.com/assets/4179257/426332/c19a0ae2-adc5-11e2-8a23-cf5c74387f1b.png)
will result in the same range of visualization:
![image](https://f.cloud.github.com/assets/4179257/426329/9da1d7c8-adc5-11e2-931a-9da66030b9d5.png)

It works correctly when removing any one of them.

**Comment by pidugusundeep** [comment]
@TMWong can you give me a sample zip with a simple html file iam still unable to get the BRAT eanabled even after following all the steps mentioned in [http://brat.nlplab.org/embed.html](http://brat.nlplab.org/embed.html)
