### ISSUE TITLE
Cannot install brat

### ISSUE THREAD

**Issue by ghost** [nlplab/brat#1052]
Hi,
I installed Brat in an Ubuntu Server following the instructions on the manual at     http://brat.nlplab.org/installation.html.

I wanted to verify that brat is running by opening a web browser (Safari and Chrome), but I get three error messages. I attach a screenshot.

![captura de pantalla 2013-10-10 a las 10 38 45](https://f.cloud.github.com/assets/5651954/1303242/c7a55b8e-314c-11e3-9bab-a63b90f49aaf.png)

Then, I tried issuing

 ./troubleshooting.sh url_to_brat_installation

And I get the following results:

WARNING: No url scheme given, assuming scheme: "http", netloc: "url_to_brat_installation" and path: "/"
Traceback (most recent call last):
  File "./troubleshooting.py", line 124, in <module>
    exit(main(argv))
  File "./troubleshooting.py", line 76, in main
    res = _request_wrap(conn, 'HEAD', url_soup.path)
  File "./troubleshooting.py", line 30, in _request_wrap
    headers=headers if headers is not None else {})
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

Do you have any idea why the installation doesn't work?

Thank you in advance,

M. Pilar

**Comment by WL-ICT** [comment]
Hi, I have met the same problem as you when I tried to install brat on MAC. 

Didn't receive json data when accessing "http://103.6.87.112//ajax.cgi".
Have you perhaps forgotten to add a handler for CGI in your web server
configuration?

You said you modified the file "/etc/apache2/sites-available/default" and fixed the problem, but I can't find that file in the directory of apache where it installed.

Could you tell me how to solve it? Thank you very much!

**Comment by ShanikaEdiriweera** [comment]
@ghost which file exactly did you modify?
/etc/apache2/sites-available/default-ssl.conf OR /etc/apache2/sites-available/000-default.conf

And could you please give what you changed exactly (the config lines)?

**Comment by kushalbabel** [comment]
apache2.conf should look like this if you have installed brat in /var/www/html

```
<Directory /var/www/>
	Options Indexes FollowSymLinks
#	AllowOverride None
	Require all granted
	AddType application/xhtml+xml .xhtml
	AddType font/ttf .ttf
	# For CGI support
	AddHandler cgi-script .cgi
</Directory>

<Directory /var/www/html/>
	AllowOverride Options Indexes FileInfo Limit
	AddType application/xhtml+xml .xhtml
	AddType font/ttf .ttf
	# For CGI support
	AddHandler cgi-script .cgi
	# Comment out the line above and uncomment the line below for FastCGI
	#AddHandler fastcgi-script fcgi
</Directory>

```
For any other location, please use your head
