### ISSUE TITLE
Tick boxes for attributes

### ISSUE THREAD

**Issue by jnferfer** [nlplab/brat#1060]
Hello,

By reading the documentation, I can't figure out how to edit the properties of attribute visualization. I wonder if I can display them in the form of tick boxes, instead of the drop-down menus. Any suggestions?

Thanks,

Juan

**Comment by soluna1** [comment]
Hello, 
I'm interested in configuring an attribute with 3 possible options to tick in boxes (instead of a drop-down menu), is that possible? How?
Thanks, 

Sisi
