### ISSUE TITLE
Error listing data directory on standalone.py server

### ISSUE THREAD

**Issue by oskar-j** [nlplab/brat#1099]
Hi,

I am running a standalone Brat, and I configured dirs to below:
Previously I had 

``` python
DATA_DIR = path_join(BASE_DIR, 'data')
```

and kept a symlink called 'github' in the standard /data subdirectory, but the error was the same. I though it's the symbolic link fault, but the config below didn't help:

``` python
BASE_DIR = dirname(__file__)
DATA_DIR = '/mnt/data1/oskar/brat-data/'  # path_join(BASE_DIR, 'data')
WORK_DIR = path_join(BASE_DIR, 'work')
```

So, first screen which welcomes me is the "Open" dialog. I click on the "github" directory, I wait a moment, and again "Open" window shows, but this time with a list of all text files which are there. (BTW, I cannot click on any of them, there is about 98k of them, JS error?). I finally press the Ok button (happy to start with the first file), wait a while, and bellow error shows:

![alt text](http://www.users.pjwstk.edu.pl/~osj/brat/err-stand-brat.png)

![alt text](http://www.users.pjwstk.edu.pl/~osj/brat/err-stand-brat2.png)

```
Serving brat at http://127.0.0.1:8001
Traceback (most recent call last):
  File "server/src/server.py", line 322, in serve
    return _safe_serve(params, client_ip, client_hostname, cookie_data)
  File "server/src/server.py", line 197, in _safe_serve
    json_dic = dispatch(http_args, client_ip, client_hostname)
  File "server/src/dispatch.py", line 308, in dispatch
    json_dic = action_function(*action_args)
  File "server/src/document.py", line 513, in get_directory_information
    stats_types, doc_stats = get_statistics(real_dir, base_names)
  File "server/src/stats.py", line 62, in get_statistics
    or getmtime(get_config_path(directory)) > cache_mtime):
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I put a visual.conf in /mnt/data1/oskar/brat-data/

Can you please help, why the path in error have subdir doubled ?
My university won't allow to install it to Apache.
Thank you very much!!

**Comment by outsideMyBox** [comment]
It happened to me as well. I got the errors after changing the data's path. 
The errors seem to be due to the files .stats_cache. Deleting all of them before restarting the server corrects the issue.

**Comment by demongolem** [comment]
I too had this error and it just happened out of the sudden.  For months I had stable copy of brat that I was accessing.  Then, I tried accessing it from chrome one day and I got the above stack trace exactly.
