### ISSUE TITLE
Problems with CGI

### ISSUE THREAD

**Issue by sacca93** [nlplab/brat#1141]
Good morning everybody :)

I'm trying to install Brat on Apache Web Server 2.4 but when I go to http://localhost/brat-v1.3_Crunchy_Frog it shows me this three errors:

![erroribrat](https://cloud.githubusercontent.com/assets/6728686/7153271/9cd9ea22-e349-11e4-89bd-0c8e1a527686.png)

Then I run the troubleshooting.py script and it gives me this result:

Didn't receive json data when accessing "http://localhost/brat-v1.3_Crunchy_Frog/ajax.cgi".
Have you perhaps forgotten to add a handler for CGI in your web server configuration?

I give you a few more informations about my installation:
1) Brat is installed in this directory /var/www/html/brat-v1.3_Crunchy_Frog

2) I have modified the httpd.conf file, like the installation guide tells me, and now it looks like this:
![httpd](https://cloud.githubusercontent.com/assets/6728686/7153352/c66839f6-e34a-11e4-9ecd-747994e3a204.png)

I'm doing something wrong but I don't get what! Thank you very much for your help :)
Pietro

**Comment by ninjin** [comment]
This looks like #1136, closing as a dupe.

**Comment by TaimurAK** [comment]
Hi I could not find the solution to this issue. I am facing the exact same issue. Can you please guide me?

**Comment by kushalbabel** [comment]
apache2.conf should look like this if you have installed brat in /var/www/html

<Directory /var/www/>
	Options Indexes FollowSymLinks
#	AllowOverride None
	Require all granted
	AddType application/xhtml+xml .xhtml
	AddType font/ttf .ttf
	# For CGI support
	AddHandler cgi-script .cgi
</Directory>

<Directory /var/www/html/>
	AllowOverride Options Indexes FileInfo Limit
	AddType application/xhtml+xml .xhtml
	AddType font/ttf .ttf
	# For CGI support
	AddHandler cgi-script .cgi
	# Comment out the line above and uncomment the line below for FastCGI
	#AddHandler fastcgi-script fcgi
</Directory>

For any other location, please use your head

**Comment by ravi-ojus** [comment]
I had the following error after installation

$sudo tools/troubleshooting.sh http://localhost/brat
Didn't receive json data when accessing "http://localhost/brat/ajax.cgi".
Have you perhaps forgotten to add a handler for CGI in your web server configuration?

brat was installed in to /var/www/html/brat

Finally was able to run brat after creating the following link

$ cd /etc/apache2/mods-enabled
$ sudo ln -s ../mods-available/cgi.load
got the hit from this site: https://code-maven.com/set-up-cgi-with-apache

OS : Ubuntu 14.04
Brat : 1.3v
apache2.conf:

165 <Directory /var/www>
166 Options Indexes FollowSymLinks
167 # AllowOverride None
168 Require all granted
169 AddType application/xhtml+xml .xhtml
170 AddType font/ttf .ttf
171 # For CGI support
172 AddHandler cgi-script .cgi
173 
174
175 <Directory /var/www/html>
176 Options Indexes FollowSymLinks
177 # AllowOverride None
178 Require all granted
179 AddType application/xhtml+xml .xhtml
180 AddType font/ttf .ttf
181 # For CGI support
182 AddHandler cgi-script .cgi
183 
184
185 <Directory /var/www/html/brat>
186 AllowOverride Options Indexes FileInfo Limit
187 Require all granted
188 AddType application/xhtml+xml .xhtml
189 AddType font/ttf .ttf
190 # For CGI support
191 #AddHandler cgi-script .cgi
192 # Comment out the line above and uncomment the line below for FastCGI
193 AddHandler fastcgi-script fcgi
194 
195 # For FastCGI, Single user installs should be fine with anything over 8
196 FastCgiConfig -maxProcesses 8

Thanks for all the messages in this forum.

Ravindra
