### ISSUE TITLE
Cluttered drawing of dependency links

### ISSUE THREAD

**Issue by robertostling** [nlplab/brat#1158]
I am trying to do some annotation with the Universal-Dependency configuration shipped with brat, but the dependency links are drawn in such a poor way that it's nearly impossible to see the structure with all the overlapping labels and arrows. The same goes for the TDT example, across different browsers (Chromium and Firefox) and brat versions (latest git version, and release 1.3).

Is there any way to get something more like the examples in the UD documentation, which are neat and readable?

I should add that the TDT looks good on the demo server as well, so I guess there is some difference between that setup and the default settings.

**Comment by spyysalo** [comment]
That's odd, the layout algorithm should be identical to that used in the UD documentation. Could you please post an example (.txt, .ann and an image of problematic layout)?

**Comment by robertostling** [comment]
It seems the problem is related to the fact that I increased font size to 40px (since the default 13px is useless when annotating Chinese) in `static/style-vis.css`. When I reset it to 13px at least the TDT example looks good again.

Here is a [screenshot](http://imgur.com/B4fc9gRl), using the Universal-Dependencies configuration from the latest github version and [mengzi.ann](http://pastebin.com/kueaXW7p) + [mengzi.txt](http://pastebin.com/cXTJiJe5).

If there is any better way of making Chinese annotation possible except editing `style-vis.css` I'd be happy to hear.

**Comment by spyysalo** [comment]
Ah, it's Chinese! You'll want to run a tokenizer; the algorithm wants to be able to move words around to make the layout reasonable.

It would probably be easiest to just explicitly add space characters into the source text (thin unicode space should do), but if you want to do things "properly" and/or can't modify the text, you can integrate a tokenizer following the example of how Japanese tokenizers are used in brat.

**Comment by robertostling** [comment]
Thanks!

I was hoping it would be possible to do the segmentation in brat at the same time as the POS annotation, but since this is Classical Chinese I suppose a thin space between every character in the original text would be a reasonable workaround.

**Comment by spyysalo** [comment]
Great, hope it works! I'll close this, but please feel free to reopen if the workaround is not satisfactory.
