### ISSUE TITLE
Can't use ':' in dependency labels

### ISSUE THREAD

**Issue by ftyers** [nlplab/brat#1163]
Hey! Is it possible to include support for using `:` in dependency labels like are used in UD, e.g. 

```
nmod Arg1:<TOKEN>, Arg2:<TOKEN>
nmod:own Arg1:<TOKEN>, Arg2:<TOKEN>
```

Gives the error:

```
Note: in configuration, term 'nmod:own' is not appropriate for storage (should match '^[a-zA-Z0-9_-]*$'), using 'nmod_own' instead. (Revise configuration file to get rid of this message. Terms other than the first are not subject to this restriction.)
```

Or is there some other way to do this ?

**Comment by spyysalo** [comment]
You can have any character appear in the UI, just set it in `visual.conf`. The file format is, however, constrained as indicated by the error.
