### ISSUE TITLE
File "standalone.py", line 257     except SystemExit, sts:

### ISSUE THREAD

**Issue by aaohmgd** [nlplab/brat#1237]
I have found the following syntax error :
**File "standalone.py", line 257
    except SystemExit, sts:**
when I run the command:
**python standalone.py**
Please let me know how can I fix this problem on Mac  
Many thanks

**Comment by JohnGiorgi** [comment]
Check that you are running 'python2.7'

In Terminal, run 'python2.7 standalone.py'

**Comment by aaohmgd** [comment]
Many thanks you for your quick.
