### ISSUE TITLE
Which is the method to sort annotations over a token?

### ISSUE THREAD

**Issue by joancf** [nlplab/brat#1248]
I use brat embedded and I can manage to display several annotations over a single token. For example Lemma and Pos, but I don't know how to say or how does Brat decide which one goes over/under the other. So sometimes I have the lemma on top, and others under the POS.
There is any way to force that?  It seems that relations change that, but there is no way to define which should go in top?

As a sample you can check this code in the  http://brat.nlplab.org/embed.html page 

`{
    "entity_types": [
        {
            "type": "Person",
            "labels": [ "Person", "Per" ],
            "bgColor": "#7fa2ff",
            "borderColor": "darken"
        },
      {
            "type": "lemma",
            "labels": [ "Lemma" ],
            "bgColor": "#7fa2ff",
            "borderColor": "darken"
        }
    ]
}`

`{
    "text": "Ed O'Kelley was the man who shot the man who shot Jesse James.",
    "entities": [
        [
            "T1",
            "Person",
            [ [ 0, 11 ] ]
        ],
        [
            "T2",
            "Person",
            [ [ 20, 23 ] ]
        ],
        [
            "T3",
            "Person",
            [ [ 37, 40 ] ]
        ],
     [
            "T5",
            "Person",
            [ [ 50, 61 ] ]
        ],
          [
            "T6",
            "lemma",
            [ [ 0, 11 ] ]
        ],
        [
            "T7",
            "lemma",
            [ [ 20, 23 ] ]
        ],
        [
            "T8",
            "lemma",
            [ [ 37, 40 ] ]
        ],
     [
            "T9",
            "lemma",
            [ [ 50, 61 ] ]
        ]
    ],
   
    "relations": [
        [
            "R1",
            "Anaphora",
            [ [ "Anaphor", "T2" ], [ "Entity", "T1" ] ]
        ]
    ],
    "triggers": [
        [
            "T5",
            "Assassination",
            [ [ 45, 49 ] ]
        ],
        [
            "T6",
            "Assassination",
            [ [ 28, 32 ] ]
        ]
    ],
    "events": [
        [
            "E1",
            "T5",
            [ [ "Perpetrator", "T3" ], [ "Victim", "T4" ] ]
        ],
        [
            "E2",
            "T6",
            [ [ "Perpetrator", "T2" ], [ "Victim", "T3" ] ]
        ]
    ]
}`

**Comment by reckart** [comment]
If I understand it correctly, then the "Persons" are moved up in all cases but the last because of the relations attached to them.  I guess in the last case, the "Lemma" is in the upper position because "L" < "P" and there are no relations involved.

My best guess at the moment is that the relevant code is the "fragmentComparator" here:

https://github.com/nlplab/brat/blob/0c430b28abebf8df700eb4096c0f14a55cdc16a7/client/src/visualizer.js#L479-L526
