### ISSUE TITLE
got 'Rendering terminated due to: DOMException'

### ISSUE THREAD

**Issue by suiyuan2009** [nlplab/brat#1275]
got 
```
Rendering terminated due to: DOMException: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (29) is greater than the maximum bound (25)
```
, page can't show the article. also got 
```
Uncaught TypeError: that.handleAsynchError is not a function at dispatcher.js:77
```
,running brat with `python standalone.py`.

**Comment by suiyuan2009** [comment]
this is a chrome browser problem.

**Comment by kwalcock** [comment]
This chrome browser problem is currently also affecting Firefox and Edge.  We're having to resort to Safari to display some pages.  The issue needs to be revisited.  See also #1363, #1220.

**Comment by kwalcock** [comment]
Replacing visualizer.js and util.js in client/src with master branch's version seems to have fixed the problem though.  Thanks.
