### ISSUE TITLE
Font size become condensed after 100 lines

### ISSUE THREAD

**Issue by pnvphuong** [nlplab/brat#1280]
Have you encountered this problem that all text become condensed and almost impossible to read or annotate when approaching more than 100 lines? (a screenshot is attached below)
Would you show me how to solve this?
Thank you!

![screenshot](https://user-images.githubusercontent.com/4739533/44494317-2a153f80-a620-11e8-9316-9f77d208e131.png)

**Comment by pnvphuong** [comment]
Turn out the error comes from the emoticon "word". I wonder if is there any solution for this problem but not delete the emoticon?
Thanks

**Comment by reckart** [comment]
@pnvphuong You could give [WebAnno](https://webanno.github.io/webanno/) a try. It uses a modified version of the brat rendering engine and I believe that we already had users that worked with these kinds of unicode characters. No promises though.

**Comment by pnvphuong** [comment]
Thanks @reckart . I will give it a try.
