### ISSUE TITLE
Error binding to port 8001 : Address already in use

### ISSUE THREAD

**Issue by sylwiaoz** [nlplab/brat#1282]
Hello,
I'm getting the following error message after intalling brat as a standalone server: Error binding to port 8001 : Address already in use.
Can you help?
Cheers
Sylwia

**Comment by JohnGiorgi** [comment]
Something else is using that port (maybe another running instance of the Brat server?). Try to

- figure out what that is and close it (if you don’t need it running)
- close your terminal app, that will close any command line app using the port
- see if you can choose another port number when you startup the brat server

**Comment by icedwater** [comment]
@sylwiaoz did you solve this already? It would be nice if you could close the issue :)
