### ISSUE TITLE
Unable to annotate multiple lines

### ISSUE THREAD

**Issue by Dawny33** [nlplab/brat#1285]
Whenever I try to highlight multiple lines, Brat shows the following error:

`text bound annotation shorter than marked span`

Attaching the screenshot for your reference:

<img width="894" alt="screen shot 2018-09-23 at 8 30 56 pm" src="https://user-images.githubusercontent.com/4637008/45929499-59e19b00-bf70-11e8-9cc8-3e155d2cd78b.png">

**Update:**
It either throws me that error above, or collapses into a tiny span whose text is not available.

Brat Version: v1.3

Test file: 
[6127.txt](https://github.com/nlplab/brat/files/2413564/6127.txt)

**Steps to reproduce:**
Try to annotate the file from L4-7

**Comment by amadanmath** [comment]
Result on the current version:
![Result on the current version](https://user-images.githubusercontent.com/134244/45989881-71c43680-c0b8-11e8-9eba-60fc34dbb353.png)

**Comment by Dawny33** [comment]
@amadanmath  Is this v1.3 or the bleeding edge one, like you suggested on SO?

**Comment by amadanmath** [comment]
Edge. As I said, v1.3 package is at least 20-50 bugs/features behind, and the only appropriate response is "upgrade".

**Comment by Dawny33** [comment]
@amadanmath Thanks. Getting this error now.  Given 077 permissions already.

Possible to help me with this please? 

<img width="684" alt="screen shot 2018-09-25 at 8 30 05 am" src="https://user-images.githubusercontent.com/4637008/45990316-4c75ff00-c09d-11e8-8a14-1711b1f64738.png">

**Comment by amadanmath** [comment]
`077` permissions mean you are not able to read, write or enter the directory (but your group and everyone else is). You likely wanted `777`? Check just in case `ls -lad /path/to/brat/work`

**Comment by Dawny33** [comment]
Thanks @amadanmath . The bleeding edge version is working perfectly.
