### ISSUE TITLE
Cannot annotate (seems to be caused by bug with credentials)

### ISSUE THREAD

**Issue by alaindesilets** [nlplab/brat#1296]
I am running the current GitHub version of brat, because I need Python3 support.

I run standalone.py using Python 3 on OSX, and it seems that the credentials I enter with Login do not persist. This is preventing me from annotating documents. Here is how to reproduce the bug:

- Click Login and enter valid user id and pwd
- Create an annotation and submit it
- The system will refuse to do it and print error message: ''ERROR: Login required to perform "createSpan"'

I did a bit of investigation using the PyCharm debugger, and it seems that when I submit my annotation, the brat server creates a brand new CURRENT_SESSION, using a cookie with a brand new sid, instead of using the one that is currently active (and contains the user name).

The call stack is:

init_session, session.py:159
_safe_serve, server.py:186
serve, server.py:338
run_brat_direct, standalone.py:183
do_POST, standalone.py:236
handle_one_request, server.py:406
handle, server.py:418
__init__, socketserver.py:696
finish_request, socketserver.py:361
process_request, socketserver.py:614
_handle_request_noblock, socketserver.py:317
serve_forever, socketserver.py:238
main, standalone.py:295
<module>, standalone.py:308

**Comment by mmxgn** [comment]
I have a similar problem. Login required to perform "createArc"

**Comment by amadanmath** [comment]
Sorry for the slow response. I was working on another bug on python2 branch that I thought was it when I noticed your message, which coincidentally was at the same time and displayed much of the same symptoms, but finally turned out to be unrelated T_T

Should be working now, I hope.

**Comment by mmxgn** [comment]
Can confirm. It works!

Thanks for fixing this.

**Comment by alaindesilets** [comment]
Likewise here. Thx
