### ISSUE TITLE
Unable to parse the following line(s): error when .ann is obtained partly automatically and partly manually

### ISSUE THREAD

**Issue by Branislava** [nlplab/brat#1301]
I perform NER with a certain tool and export an output in a standoff format. 

T900	PERS 403 409	Gerald
T901	PERS 552 558	Birkin
T902	MISC 673 676	two
T903	PERS 765 771	Birkin

Then I open this .txt/.ann from the brat interface, and annotate manually what's left to be annotated.
Everything is displayed perfectly until I start performing manual annotation.
My generated tokens begin with T90... because I do not want ambiguous identifiers (those obtained manually start from T1, T2, etc.)

The message I get is:
Unable to parse the following line(s):
T900	PERS 403 409	Gerald

This token is the only one not coloured. After the warning vanishes, all other tokens are nicely coloured and annotated.
When I delete .ann file and annotate this token itself, the line *is identical* to the one I obtained programmatically.

When I put this first line, e.g, at the end of the file, this token becomes now annotated, but then I get the same warning for the token from the second line 

T901	PERS 552 558	Birkin

and then this token is not annotated anymore.

The behavior is the same with other files I have.

Thank you in advance.

**Comment by jjon** [comment]
Just a thought: I had a similar problem some time ago that I finally traced to the presence of a byte order mark at the top of my file. Some automated tools generate BOM files by default.

**Comment by Branislava** [comment]
> Just a thought: I had a similar problem some time ago that I finally traced to the presence of a byte
> order mark at the top of my file. Some automated tools generate BOM files by default.

This is it, thank you a lot!
