### ISSUE TITLE
Can not edit or create new annotations

### ISSUE THREAD

**Issue by JannicBeck** [nlplab/brat#1326]
Navigate e.g. to http://weaver.nlplab.org/~brat/demo/latest/#/editable/tutorials/bio/000-introduction

I can not edit or create new annotations. The console also throws an error:
Failed to load resource: net::ERR_INVALID_URL

**Comment by varun-tandon** [comment]
@JannicBeck I played around with this for a while, my issue ended up being that I had not logged in. 

You need to login in order to start making annotations, and can do so by hovering over the top bar and then clicking "Login"

**Comment by JannicBeck** [comment]
Thanks @varun-tandon. I was running brat locally and somehow got logged out.
