### ISSUE TITLE
can we restrict access to that or that folder according to the username ?

### ISSUE THREAD

**Issue by jeanphilippegoldman** [nlplab/brat#1337]
Hi, 
Is there any advanced user management , especially on managing specific folder access ?

In other words, can we restrict access to that or that folder according to the username ?
The reason can be:
1.I want to make a parallel annotation by several annotators: so I duplicate documents in several folders but I want to allow annotators to access to their folder only.
or,2. a part of my data is sensitive, I have several annotations projects in parallel, and I want  to prevent some annotators to access to this data.

Or am I missing something ?
Thanks for your suggestions

**Comment by jeanphilippegoldman** [comment]
After browsing many similar requests and the code, here is my functionning experience on linux:

1. define pairs of username:password in config.py. e.g 
  annotator1:weakpassword1
  annotator2:weakpassword2

2. duplicate data to annotate with as many folders as annotators, eg.
annotator1/
annotator2/

3. within each of these folders, create a simple acl.conf
User-agent: *
Disallow: /

User-agent: annotator1
Allow: /

Please, reopen this ticket if you have suggestions or questions.

**Comment by kovvalsky** [comment]
I would be nice to do this with one `acl.conf`.

Create `data/annotate/acl.conf` with the content:
```
  User-agent: *
  Disallow: /*/annotate

  User-agent: annotator1
  Allow: /*/annotate/annotator1

  User-agent: annotator2
  Allow: /*/annotate/annotator2
```
Creating several `acl.conf` can be done automatically but in case of some changes in annotator groups, doing this modification by hand across several `acl.conf` is not handy.

My current situation is: 20 annotator groups of 2 annotating different parts of corpus. If annotators withdraw from the group, changing several `acl.conf` is not handy. I prefer to change only one `acl.conf`.
