### ISSUE TITLE
First time clicking Norm List Dialog OK button in each tab results in full page reload

### ISSUE THREAD

**Issue by jeffmax** [nlplab/brat#1351]
I believe the fix is just to add a `return false;` here: https://github.com/nlplab/brat/blob/master/client/src/annotator_ui.js#L1144

I am not sure why it is only an issue the first time the button is clicked.

**Comment by amadanmath** [comment]
I can't really reproduce (maybe because it's not my first time?), but I'll trust you and add the line.
