### ISSUE TITLE
is it possible to pip install parts of brat?

### ISSUE THREAD

**Issue by joseberlines** [nlplab/brat#1377]
I have a text string and a data structure that gives me already the NERs of the text as such:

```
[{name: 'organization', start:56, lenght: 45},
{name: 'person', start:156, lenght: 23},...]
```

Can I use brat  to visualize (not to annotate) that particular document?
Is there in the brat project any pip installable module to generate the HTML with NERs by combining the text and the spans above mentioned?

thanks

**Comment by ghost** [comment]
Yes and no, but these are not bugs so closing.
