### ISSUE TITLE
Download link on website is dead

### ISSUE THREAD

**Issue by ehrhart** [nlplab/brat#1382]
As of today, on the web page https://brat.nlplab.org/downloads.html, the link to download _brat v1.3 (Crunchy Frog)_ returns "Page Not Found".

Additionally, links to the previous releases also return the same error.

**Comment by TdioXL** [comment]
https://github.com/nlplab/brat/releases/tag/v1.3p1
download this

**Comment by EBoiSha** [comment]
How about fixing it? :D

**Comment by wkiri** [comment]
Try the Crunchy Frog release here: https://github.com/nlplab/brat/releases/tag/v1.3_Crunchy_Frog (slightly pre-dates v1.3p1).

**Comment by ghost** [comment]
Thank you again @wkiri, fixed.
