### ISSUE TITLE
The server encountered a serious error, please contact the administrator.

### ISSUE THREAD

**Issue by shaitaiyangmie** [nlplab/brat#1385]
Hello, there are some questions when I load the .ann documents and .txt documents which I write, like the picture below.
![image](https://user-images.githubusercontent.com/73834112/156021095-a5e88d62-248d-4bb7-bc69-adb703a86ad7.png)
I do not understand what the -1 meaning and how to avoid this problem. Please help me, thanks a lot!

**Comment by ghost** [comment]
Probably a format error, but impossible to debug without more information. Closing.
