### ISSUE TITLE
How to remove "delete warnings dialog"?

### ISSUE THREAD

**Issue by unikcc** [nlplab/brat#1388]
Whenever I click delete button, the web page  will always give a dialog box to ensure the delete operation.
This design is awesome but sometimes it's annoying, especially when I need to delete batch of annotation.
I'm not familiar with the source code of brat, so I want to know **how to modify the code to remove the "delete warnings dialog"** and I can click the delete button to accomplish deletion directly. 
![image](https://user-images.githubusercontent.com/19505579/157361738-5d4cedb0-0fa7-4d60-a33e-d781fb72771f.png)

**Comment by ghost** [comment]
There are multiple annotation modes. Check your client settings in the web UI.
