### ISSUE TITLE
Other pc can not access via ip address + port

### ISSUE THREAD

**Issue by weinixuehao** [nlplab/brat#1390]
I installed the brat on a ubuntu pc and opened the page successfully but on another pc does not work, It shows me a circle loading forever.

![image](https://user-images.githubusercontent.com/17869361/163125618-d3fa75a1-37db-4a02-bcb9-492c75045d1b.png) => mac osx M1

![image](https://user-images.githubusercontent.com/17869361/163125919-00b0382c-c4c5-4eb1-88dc-a69c47817ca2.png) => ubuntu pc

PS: Other pc can open except my computer, I suspect my computer is M1.

**Comment by ghost** [comment]
This is most likely related to your security/network policies for your operating system. Please consult your manual or operating system support as there is little we can do.
