### ISSUE TITLE
Download link On Home Page is Broken

### ISSUE THREAD

**Issue by EBoiSha** [nlplab/brat#1391]
Hi!
It seems that the download link on your homepage is broken. If I click download v1.3 here http://brat.nlplab.org/index.html
the browser responds with a DNS error

**Comment by wkiri** [comment]
It looks like you can get it at https://github.com/nlplab/brat/releases/tag/v1.3_Crunchy_Frog .

**Comment by ghost** [comment]
Excellent point @wkiri – thank you. I have updated the homepage to point directly to the correct tarball.
