### ISSUE TITLE
BRAT Standalone supporting https 

### ISSUE THREAD

**Issue by rjalexa** [nlplab/brat#1399]
I tried running the standalone script, opening my ufw linux 8001 port and access the web interface from another machine but get:
`195.220.213.127 - - [30/Nov/2022 09:45:00] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x08\xfb\x85g\xc2\xa9\x1c\xe5\xda\xca\xe4\x08\xdf\xfb\xb3\xb8\xca\x13\xe8v\xfa\xe1CZ\xe6\xe2\xf5W\x1d\xc1\xda\xcc \x82\x96\x1f2\xf1-\x9a\xfcE\xbd\xfc\x88\xd0\xc0\xee+\r1\x8a(\x931\x8a%\xbf\x14+S`|\x04\r\x00 \xfa\xfa\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x9a\x9a\x00\x00\x00\x00\x00\x0f\x00\r\x00\x00')` 
on the local shell and the remote browser says it cannot connect to https.

Is there a way to achieve this? Thanks

**Comment by ghost** [comment]
The stand-alone script does not support HTTPS. If you want HTTPS, set up a “real” web server.
