### ISSUE TITLE
BRAT demo does not work

### ISSUE THREAD

**Issue by ciceronianus** [nlplab/brat#1400]
This is about the website https://brat.nlplab.org/index.html. When I click on Online Demo (http://weaver.nlplab.org/~brat/demo/latest/), nothing happens. Tested in multiple web browsers. 
I hope it is fine that I post it here.

**Comment by xiulinyang** [comment]
It is still not working. :(

**Comment by wsong1106** [comment]
Still not working now..

**Comment by SeventeenCui** [comment]
Still not working now..

**Comment by ghost** [comment]
Removed references to demo as the server is long dead due to lack of funding.
