### ISSUE TITLE
Word Segmentation for Japanese

### ISSUE THREAD

**Issue by ghost** [nlplab/brat#164]
In order to be able to lay out Japanese text we first need to find word boundaries, for this we need an external tool.

**Comment by sunmoonStern** [comment]
Hello, does brat work with MeCab? My tools.conf looks like this and I am using brat for annotation for some time now but I don't think brat is recognizing different words/tokens. MeCab can be used to generate output in several different formats. Could you tell me what kind of output is brat assuming? Thanks in advance.

```
[options]

# Possible values for validate:
Validation	validate:all

# Possible values for tokenizer
Tokens tokenizer:mecab
#Tokens	   tokenizer:whitespace

# Possible values for splitter:
Sentences	splitter:regex

# Possible values for logfile:
Annotation-log logfile:<NONE>

[search]
Google       <URL>:http://www.google.com/search?q=%s
Wikipedia    <URL>:http://en.wikipedia.org/wiki/Special:Search?search=%s

[annotators]

[disambiguators]

[normalization]

```
