### ISSUE TITLE
Annotations at sentence level

### ISSUE THREAD

**Issue by illes** [nlplab/brat#326]
Ability of having annotations on the sentence level would help in cases where annotators should consider only a few relevant sentences (relevance determined automatically in advance). Deleting irrelavant sentences in this case would be an alternative solution, but would remove the necessary context.

**Comment by vlordier** [comment]
So, back to this : is there a simple way to annotate sentences directly now ?

**Comment by amadanmath** [comment]
Took a while, but sentence-level annotation is implemented as of 550ff1b — double-click on sentence number to edit.
