### ISSUE TITLE
Attribute visuals should be in visual.conf, not annotation.conf

### ISSUE THREAD

**Issue by spyysalo** [nlplab/brat#665]
The current way to define visuals for multi-valued attributes is to have something like this in `annotation.conf`:

```
Manner  Arg:<EVENT>, High:↑, Low:↓, Neutral:↔, <DEFAULT>:Neutral
Polarity    Arg:<EVENT>, Negative:✕, Positive:✓, <DEFAULT>:Positive, <GLYPH-POS>:left
```

This mixes content with presentation. `annotation.conf` should only contain the definition of the possible values for the attribute; `visual.conf` should contain the info on glyphs and their position.

**Comment by soluna1** [comment]
hi, is it possible to set the color of the background for each attribute, like
polarity     value:positive, bgColor:lightgreen
???
thanks
