### ISSUE TITLE
Converting (*.txt & *.ann) into CoNLL, both ways?

### ISSUE THREAD

**Issue by fsalotaibi** [nlplab/brat#834]
Hi brat's team,

I wonder if there is an out of the box script to convert the (_.txt &_.ann) files into CoNLL version. In CoNLL, each token is represented in one line associating with the proper tag.

e.g. "The <ORG>British Olympic Association</ORG> chairman says Chinese swimmer <PER>Ye Shiwen</PER> is not a drug cheat ..."

This is represented in CoNLL as:
The                     O
British                 B-ORG
Olympic              I-ORG
Association         I-ORG
chairman          O
says              O
Chinese         O
swimmer        O
Ye                 B-PER
Shiwen          I-PER
is                   O
not                 O
a                    O
drug               O
cheat              O
- I wonder if you came across such script to do so?
- What about if I want to convert a CoNLL file I have to work into brat?

Fahd

**Comment by pidugusundeep** [comment]
just want to understand how do i use that anntoconll.py file to generate the IOB file with .ann file ?

**Comment by wbj0110** [comment]
yes

**Comment by ZohaibRamzan** [comment]
> just want to understand how do i use that anntoconll.py file to generate the IOB file with .ann file ?

How?
