### ISSUE TITLE
How to convert brat standoff format so can train Stanford NER?

### ISSUE THREAD

**Issue by neilmcguigan** [nlplab/brat#996]
Hello,

I would like to annotate some documents with brat, and then train Stanford NER to recognize those entities, so that I can recognize unseen documents in the future.

a) is this a good idea?

b) is there an easy way to convert brat standoff format into a format that Stanford NER can use easily?

Thanks!

Neil

**Comment by thatguysimon** [comment]
Not sure what was the required format back in 2013, but the training data format required today by NER is very different from the CoNLL format, see: [http://nlp.stanford.edu/software/crf-faq.html#a](http://nlp.stanford.edu/software/crf-faq.html#a)

Here's a gist I made that turns data in the standoff format into the format described above, as well as the format required for the Stanford Relation Extractor. Might be useful for future visitors who stumble upon this page like I did. 
[https://gist.github.com/thatguysimon/6caa622be083f97b8c5c9a10478ba058](https://gist.github.com/thatguysimon/6caa622be083f97b8c5c9a10478ba058)

**Comment by toliwa** [comment]
@thatguysimon Sometimes, named entities might have a period in them, depending on the domain. I encountered this while trying your gist, and made a code change that can resolve a particular instance of this problem. I do not know how this behaves in general, but I added it as comment below your gist. 

Any ideas on how this could be further improved to handle cross-sentence annotations?

**Comment by pidugusundeep** [comment]
How do i use this file ? where do i send link the file .ann and then get the result in anntoconll.py ??
